# Generated by Django 5.0.6 on 2026-04-25 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encomienda',
            options={},
        ),
        migrations.RemoveField(
            model_name='encomienda',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='encomienda',
            name='volumen_cm3',
        ),
    ]
